"""add_cv_url_to_users_and_portfolio_config

Revision ID: 6e5717f426aa
Revises: 4711f9ef2bf5
Create Date: 2026-09-27 15:00:36.614008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5717f426aa'
down_revision: Union[str, Sequence[str], None] = '4711f9ef2bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_config', sa.Column('cv_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cv_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cv_url')
    op.drop_column('portfolio_config', 'cv_url')
    # ### end Alembic commands ###
